### ISSUE TITLE
HW08 Final Web App Develoment

### ISSUE THREAD

**Issue by yusong-shen** [yusong-shen/comp531-web-development#1]
In this assignment you will deliver your multi-user web application. The objectives are:

- generate a unified feed of articles for a user based on their followed users (partially done)
- add a redis caching store for session management (done)
- permit users to upload profile avatars and articles with pictures (done)
- add a third-party authentication option with account linking (partially done)

TODO : 
- Keep content when refreshing the page
- Preview the image
- Add user avatar besides their comment and post
- get article endpoint by its author

**Comment by yusong-shen** [comment]
`                const cookieValue = generateCode(userObj)
                // sessionUser[cookieValue] = username
                redis.hmset(cookieValue, userObj)`


node_redis: Deprecated: The HMSET command contains a argument of type InternalCache.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a argument of type Object.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a argument of type Object.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a argument of type Object.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a argument of type NativeConnection.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a argument of type ObjectID.
This is converted to "5830c79a34ca90b9eadedb15" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a argument of type Schema.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
node_redis: Deprecated: The HMSET command contains a argument of type NativeCollection.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
::1 - - [Fri, 02 Dec 2016 21:47:14 GMT] "POST /login HTTP/1.1" 200 42 "-" "python-requests/2.11.1"

**Comment by yusong-shen** [comment]
::1 - - [Sun, 11 Dec 2016 07:43:37 GMT] "GET /auth/google/login HTTP/1.1" 302 0 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
call middlewareCORS()
{ host: 'localhost:3000',
  connection: 'keep-alive',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36',
  'x-client-data': 'CJG2yQEIpLbJAQjEtskBCKmdygE=',
  'x-chrome-connected': 'id=107899790953748543552,mode=0,enable_account_consistency=false',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'accept-encoding': 'gzip, deflate, sdch, br',
  'accept-language': 'en,zh-CN;q=0.8,zh;q=0.6',
  cookie: 'connect.sid=s%3AXTon-TK7Z2YZ6MIyHtAJiU--ewtTIL4U.3h0zqjSXGV3L9%2F2QneSn%2BQvJAg6xF0637ro6WT1Qhio' }
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/Users/yusong/Code/comp531-web-development/hw8/backend/node_modules/passport-oauth2/lib/strategy.js:370:17)
    at /Users/yusong/Code/comp531-web-development/hw8/backend/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /Users/yusong/Code/comp531-web-development/hw8/backend/node_modules/oauth/lib/oauth2.js:177:18
    at ClientRequest.<anonymous> (/Users/yusong/Code/comp531-web-development/hw8/backend/node_modules/oauth/lib/oauth2.js:148:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
::1 - - [Sun, 11 Dec 2016 07:44:58 GMT] "GET /auth/google/callback?code=4/L69L0cZsnRFpUnkcdcHNOoEXwQus4gPDEBx5WT1fguw HTTP/1.1" 500 1094 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"

**Comment by yusong-shen** [comment]
http://stackoverflow.com/questions/21129989/internaloautherror-failed-to-obtain-access-token
